---
resources:
- name: indicator-protocol-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/indicator-protocol-release.git
    branch: master
    private_key: {{event-producer-github-key}}
- name: indicators
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/indicators.git
    branch: master
    private_key: {{event-producer-github-key}}
- name: env-state
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/denver-locks.git
    private_key: {{event-producer-github-key}}
- name: release-version
  type: semver
  source:
    initial_version: 0.0.1
    driver: s3
    bucket: indicator-protocol-release-version
    region_name: us-east-2
    key: version
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
- name: github-release-drafts
  type: github-release
  source:
    user: cloudfoundry-incubator
    repository: indicators
    access_token: {{event-producer-github-token}}
    drafts: true
- name: indicator-protocol-final-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/indicator-protocol-release.git
    branch: master
    private_key: {{event-producer-github-key}}
    ignore_paths:
    - .final_builds
    - releases
- name: pcf-kpis
  type: git
  source:
    uri: git@github.com:pivotal-cf/pcf-kpis.git
    branch: master
    private_key: {{event-producer-github-key}}
- name: cf-indicators-docs
  type: s3
  source:
    region_name: us-east-2
    bucket: cf-indicators-doc-tests
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    versioned_file: healthwatch.html

jobs:
- name: build-and-test
  plan:
  - aggregate:
    - get: indicators
      trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      run:
        path: bash
        args:
          - -c
          - |
            #!/usr/bin/env bash

            set -exu

            pushd indicators
              scripts/test.sh
            popd

- name: indicator-docs
  plan:
  - aggregate:
    - get: indicators
      passed: [build-and-test]
      trigger: true
  - task: generate-docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash

          set -exu

          export GO111MODULE=on

          pushd indicators/
            go run -mod=vendor cmd/docs/main.go example.yml
          popd

- name: upload-test-docs-to-s3
  plan:
  - aggregate:
    - get: indicators
      passed: [indicator-docs]
    - get: pcf-kpis
  - task: generate-and-upload-docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      - name: pcf-kpis
      outputs:
      - name: docs_out
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash

          set -exu

          export WORKSPACE=$PWD

          pushd indicators/
            go run -mod=vendor cmd/docs/main.go example.yml > ${WORKSPACE}/healthwatch_part.html
          popd

          sed '/SUBSTITUTE_HERE/{
              s/SUBSTITUTE_HERE//g
              r healthwatch_part.html
          }' ${WORKSPACE}/pcf-kpis/template.html > docs_out/healthwatch.html

  - put: cf-indicators-docs
    params:
      file: docs_out/healthwatch.html
      acl: public-read
      content_type: text/html

- name: indicator-verification
  plan:
  - aggregate:
    - get: indicators
      passed: [build-and-test]
      trigger: true
    - get: env-state
  - task: verify-metric
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      - name: env-state
      params:
        ENVIRONMENT: sunstorm
        BBL_STATE_DIR: acceptance-bosh/claimed/sunstorm
        DEPLOYMENT_NAME: cf
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash

          set -exu

          set +x
          pushd "env-state/${BBL_STATE_DIR}"
            eval "$(bbl print-env)"
          popd
          set -x

          export GO111MODULE=on

          pushd indicators/

            cat << EOF > indicators.yml
          ---
          apiVersion: v0
          product: uaa-test
          version: 0
          metadata:
            deployment: <%= spec.deployment %>
          indicators:
          - name: uaa_request_rate
            promql: rate(requests_global_status_2xx_count{source_id="uaa",deployment="\$deployment"}[10m])
          EOF

            go run -mod=vendor cmd/verification/main.go -indicators=indicators.yml \
                                                        -metadata="deployment=${DEPLOYMENT_NAME}" \
                                                        -uaa-url=https://login.${ENVIRONMENT}.cf-denver.com \
                                                        -log-cache-client=firehose_exporter \
                                                        -log-cache-client-secret=$(credhub g -n /bosh-${ENVIRONMENT}/cf/uaa_clients_firehose_exporter_secret -j | jq -r .value) \
                                                        -log-cache-url=https://log-cache.${ENVIRONMENT}.cf-denver.com \
                                                        -k

          popd

- name: bump-release-submodule
  plan:
  - aggregate:
    - get: indicators
      passed: [build-and-test]
      trigger: true
    - get: indicator-protocol-release
  - task: bump-submodule
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      - name: indicator-protocol-release
      outputs:
      - name: indicator-protocol-release-updated
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash

          set -exu

          pushd indicators
            REPO_PATH=$PWD
            SOURCE_SHA=`git rev-parse HEAD`
            COMMIT_MSG=`git rev-list --format=%B --max-count=1 $SOURCE_SHA`
          popd

          # Bumping submodule
          pushd indicator-protocol-release/src/code.cloudfoundry.org/indicators
            git remote add local $REPO_PATH
            git fetch local
            git checkout $SOURCE_SHA
          popd

          pushd indicator-protocol-release
            export GOPATH=$PWD
            export PATH=$PATH:$GOPATH/bin

            git add src/code.cloudfoundry.org/indicators

            if [[ -z $(git status -s) ]]; then
              echo "No changes to indicators submodule"
              rsync -a . ../indicator-protocol-release-updated
              exit 0
            fi

            git config --global user.email "cf-event-producer@pivotal.io"
            git config --global user.name "event-producer-cibot"
            git commit -m "Updated indicators submodule version to:\

            `echo "$COMMIT_MSG" | awk '{ print "\t"$0 }'`"
          popd

          rsync -a indicator-protocol-release/ indicator-protocol-release-updated
    on_success:
      put: indicator-protocol-release
      params:
        repository: indicator-protocol-release-updated
        rebase: true

- name: deploy-indicator-registry
  plan:
  - aggregate:
    - get: env-state
    - get: indicator-protocol-release
      trigger: true
  - task: deploy
    config:
      params:
        BBL_STATE_DIR: acceptance-bosh/claimed/sunstorm
        S3_ACCESS_KEY: {{aws-access-key-id}}
        S3_SECRET_KEY: {{aws-secret-access-key}}
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicator-protocol-release
      - name: env-state
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -ex

          set +x
          pushd "env-state/${BBL_STATE_DIR}"
            eval "$(bbl print-env)"
          popd
          set -x

          pushd indicator-protocol-release

            cat << EOF > config/private.yml
          ---
          blobstore:
            options:
              access_key_id: ${S3_ACCESS_KEY}
              secret_access_key: ${S3_SECRET_KEY}
          EOF

            bosh create-release
            bosh -n upload-release --fix --rebase

            bosh update-runtime-config -n \
              --name indicator-registration-agent \
              --var=indicator-protocol-version=$(bosh releases | grep indicator-protocol -m1 | cut -f2) \
              manifests/agent_runtime_config.yml
          popd


          bosh -n -d indicator-registry deploy \
            indicator-protocol-release/manifests/manifest.yml

- name: publish-release
  plan:
  - aggregate:
    - get: indicator-protocol-release
      passed: [deploy-indicator-registry]
    - get: indicators
      passed: [indicator-verification,indicator-docs]
      trigger: false
    - get: release-version
      params: {bump: patch}
  - task: create-final-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: release-version
      - name: indicator-protocol-release
      outputs:
      - name: final-release
      - name: github-release
      params:
        RELEASE: indicator-protocol-release
        RELEASE_NAME: indicator-protocol
        S3_BUCKET: cf-indicators-bosh-blubs
        S3_ACCESS_KEY: {{aws-access-key-id}}
        S3_SECRET_KEY: {{aws-secret-access-key}}
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash
          set -ex

          BUILD_NUMBER=$(cat release-version/number)
          tag_name="v$BUILD_NUMBER"

          # write out github release files
          echo "${RELEASE_NAME} ${tag_name}" > github-release/name
          echo $tag_name > github-release/tag
          echo "TBD" > github-release/body

          pushd $RELEASE
            cat << EOF > config/private.yml
          ---
          blobstore:
            provider: s3
            options:
              bucket_name: ${S3_BUCKET}
              access_key_id: ${S3_ACCESS_KEY}
              secret_access_key: ${S3_SECRET_KEY}
          EOF

            bosh -n create-release --sha2 --final \
              --tarball ../github-release/${RELEASE_NAME}-bosh-${BUILD_NUMBER}.tgz \
              --version "$BUILD_NUMBER"
            git add .

            git config --global user.email "cf-event-producer@pivotal.io"
            git config --global user.name "event-producer-cibot"
            git commit -m "Create final release\

            [ci skip]"
          popd

          cp -r "${RELEASE}/." "final-release/"
  - task: publish-github-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
      inputs:
      - name: indicators
      - name: release-version
      - name: github-release
      outputs:
      - name: github-release
        path: github-release-output
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash
          set -ex

          cp github-release/* github-release-output/

          BUILD_NUMBER=$(cat release-version/number)

          pushd indicators
            echo "Building darwin cli-plugin binary"
            GOARCH=amd64 GOOS=darwin go build -mod=vendor -o ../github-release-output/indicator-docs-macosx64-${BUILD_NUMBER} cmd/docs/main.go
            GOARCH=amd64 GOOS=darwin go build -mod=vendor -o ../github-release-output/indicator-verification-macosx64-${BUILD_NUMBER} cmd/verification/main.go

            echo "Building amd64 linux cli-plugin binary"
            GOARCH=amd64 GOOS=linux go build -mod=vendor -o ../github-release-output/indicator-docs-linux64-${BUILD_NUMBER} cmd/docs/main.go
            GOARCH=amd64 GOOS=linux go build -mod=vendor -o ../github-release-output/indicator-verification-linux64-${BUILD_NUMBER} cmd/verification/main.go
          popd
  - put: indicators
    params:
      repository: indicators
      rebase: true
      tag: release-version/version
      tag_prefix: v
  - put: github-release-drafts
    params:
      name: github-release/name
      tag: github-release/tag
      body: github-release/body
      globs:
      - github-release/indicator-*
  - put: release-version
    params:
      file: release-version/version
  - put: indicator-protocol-final-release
    params:
      repository: final-release
      rebase: true
      tag: release-version/version
      tag_prefix: v
