---
resources:
- name: indicator-protocol-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/indicator-protocol-release.git
    branch: master
    private_key: {{event-producer-github-key}}
- name: indicators
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/indicators.git
    branch: master
    private_key: {{event-producer-github-key}}
- name: env-state
  type: git
  source:
    branch: master
    uri: git@github.com:pivotal-cf/denver-locks.git
    private_key: {{event-producer-github-key}}

jobs:
- name: build-and-test
  plan:
  - aggregate:
    - get: indicators
      trigger: true
  - task: build-and-test
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
          tag: go-1.11
      inputs:
      - name: indicators
      run:
        path: bash
        args:
          - -c
          - |
            #!/usr/bin/env bash

            set -exu

            pushd indicators
              scripts/test.sh
            popd

- name: bump-release-submodule
  plan:
  - aggregate:
    - get: indicators
      passed: [build-and-test]
      trigger: true
    - get: indicator-protocol-release
  - task: bump-submodule
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: eventalertsdocker/pcf-event-alerts-unit
      inputs:
      - name: indicators
      - name: indicator-protocol-release
      outputs:
      - name: indicator-protocol-release-updated
      run:
        path: bash
        args:
        - -c
        - |
          #!/usr/bin/env bash

          set -exu

          pushd indicators
            REPO_PATH=$PWD
            SOURCE_SHA=`git rev-parse HEAD`
            COMMIT_MSG=`git rev-list --format=%B --max-count=1 $SOURCE_SHA`
          popd

          # Bumping submodule
          pushd indicator-protocol-release/src/code.cloudfoundry.org/indicators
            git remote add local $REPO_PATH
            git fetch local
            git checkout $SOURCE_SHA
          popd

          pushd indicator-protocol-release
            export GOPATH=$PWD
            export PATH=$PATH:$GOPATH/bin

            git add src/code.cloudfoundry.org/indicators

            if [[ -z $(git status -s) ]]; then
              echo "No changes to indicators submodule"
              rsync -a . ../indicator-protocol-release-updated
              exit 0
            fi

            git commit -m "Updated indicators submodule version to:\

            `echo "$COMMIT_MSG" | awk '{ print "\t"$0 }'`"
          popd

          rsync -a indicator-protocol-release/ indicator-protocol-release-updated
    on_success:
      put: indicator-protocol-release
      params:
        repository: indicator-protocol-release-updated
        rebase: true

- name: deploy-indicator-registry
  plan:
  - aggregate:
    - get: env-state
    - get: indicator-protocol-release
      passed: [bump-release-submodule]
      trigger: true
  - task: bump-submodule
    config:
      params:
        BBL_STATE_DIR: acceptance-bosh/claimed/sunstorm
        S3_ACCESS_KEY: {{aws-access-key-id}}
        S3_SECRET_KEY: {{aws-secret-access-key}}
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
          tag: go-1.11
      inputs:
      - name: indicator-protocol-release
      - name: env-state
      run:
        path: bash
        args:
        - -c
        - |
          #!/bin/bash
          set -ex

          set +x
          pushd "env-state/${BBL_STATE_DIR}"
            eval "$(bbl print-env)"
          popd
          set -x

          pushd indicator-protocol-release

            cat << EOF > config/private.yml
          ---
          blobstore:
            options:
              access_key_id: ${S3_ACCESS_KEY}
              secret_access_key: ${S3_SECRET_KEY}
          EOF

            bosh create-release
            bosh -n upload-release --fix --rebase

            bosh update-runtime-config -n \
              --name indicator-registration-agent \
              --var=indicator-protocol-version=$(bosh releases | grep indicator-protocol -m1 | cut -f2) \
              manifests/agent_runtime_config.yml
          popd


          bosh -n -d indicator-registry deploy \
            indicator-protocol-release/manifests/manifest.yml

- name: generate-test-docs
  plan:
  - aggregate:
    - get: indicators
      trigger: true
  - task: generate-docs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfmetrics/indicators-build-and-test
          tag: go-1.11
      inputs:
      - name: indicators
      run:
        path: bash
        args:
          - -c
          - |
            #!/usr/bin/env bash

            set -exu

            export GO111MODULE=on

            pushd indicators
              go run -mod=vendor cmd/generate_docs/main.go example.yml
            popd
