---
apiVersion: indicatorprotocol.io/v1
kind: IndicatorDocumentPatch

match:
  product:
    name: my-component
    version: 1.2.3

operations:
- type: replace
  path: /spec/indicators?/-
  value:
    name: success_percentage
    promql: success_percentage_promql{source_id="origin"}
    documentation:
      title: Success Percentage
