---
sources:
  - type: local
    path: example_patch_add_indicator.yml
  - type: local
    path: example_patch_adjust_threshold.yml
  - type: git
    repository: git@github.com:pivotal/monitoring-indicator-protocol.git
#    private_key: | # This can be provided for private repositories to be cloned through SSH
#        -----BEGIN EXAMPLE OPENSSH PRIVATE KEY-----
#        b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
#        NhAAAAAwEAAQAAAgEAzeTciXzDYaJkbjpsK67owTbfkthHrVBi1f813xjRzYNWeoUw3BDO
#        ...
#        2FyQW9gO0sYFAAAADXBpdm90YWxAb3dlbnMBAgMEBQ==
#        -----END OPENSSH PRIVATE KEY-----
#    token: abcd1234 # Can be provided for private repositories to be cloned through HTTPS
#                    # A github repository access token or password can be used
    glob: "**/*.y*ml"
