---
apiVersion: indicatorprotocol.io/v1

kind: IndicatorDocument

spec:
  product:
    name: my-product
    version: 0.1.1

  indicators:
  - name: latency
    promql: avg_over_time(demo_latency{source_id="$source_id",deployment="$deployment"}[5m])
  - name: saturation
    promql: saturation{source_id="$source_id",deployment="$deployment"}

  layout: {}


metadata:
  labels:
    deployment: spec.deployment
    source_id: demo_component
