kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-generator
  namespace: monitoring-indicator-protocol
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create"]
