kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: indicator-status-controller
rules:
- apiGroups: ["indicatorprotocol.io"]
  resources: ["indicators"]
  verbs: ["list", "update", "watch"]
