kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-generator
  namespace: monitoring-indicator-protocol
subjects:
- kind: ServiceAccount
  name: cert-generator
  namespace: monitoring-indicator-protocol
roleRef:
  kind: Role
  name: cert-generator
  apiGroup: rbac.authorization.k8s.io
