kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: indicator-admission
  namespace: monitoring-indicator-protocol
subjects:
- kind: ServiceAccount
  name: indicator-admission
  namespace: monitoring-indicator-protocol
roleRef:
  kind: Role
  name: indicator-admission
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: indicator-admission
subjects:
- kind: ServiceAccount
  name: indicator-admission
  namespace: monitoring-indicator-protocol
roleRef:
  kind: ClusterRole
  name: indicator-admission
  apiGroup: rbac.authorization.k8s.io
