apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicatordocuments.indicatorprotocol.io
spec:
  group: indicatorprotocol.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: indicatordocuments
    singular: indicatordocument
    kind: IndicatorDocument
    shortNames:
    - id
