apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: indicators.apps.pivotal.io
spec:
  group: apps.pivotal.io
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: indicators
    singular: indicator
    kind: Indicator
  additionalPrinterColumns:
  - name: Product
    type: string
    description: Product for which the indicator is defined
    JSONPath: .spec.product
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Status
    type: string
    JSONPath: .status.phase
  validation:
    openAPIV3Schema:
      required:
      - spec
      properties:
        spec:
          required:
          - name
          - promql
          properties:
            product:
              type: string
            documentation:
              type: object
            presentation:
              type: object
              properties:
                chartType:
                  type: string
                currentValue:
                  type: boolean
                frequency:
                  type: number
                labels:
                  type: array
                  items:
                    type: string
            thresholds:
              type: array
              items:
                required:
                - level
                - operator
                - value
                properties:
                  level:
                    type: string
                  operator:
                    type: string
                  value:
                    type: number
