apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-indicator-controller
  namespace: monitoring-indicator-protocol
  labels:
    app: prometheus-indicator-controller
spec:
  selector:
    matchLabels:
      app: prometheus-indicator-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-indicator-controller
    spec:
      serviceAccountName: prometheus-indicator-controller
      containers:
      - name: prometheus-indicator-controller
        image: indicatorprotocol/prometheus-indicator-controller:release-candidate
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          value: prometheus
