---
# This is invalid yaml, so it cannot be parsed (see the operator and value indentation)
apiVersion: apps.pivotal.io/v1
kind: IndicatorDocumentPatch

match:
  product:
    name: my-component-1
    version: 1.2.3

operations:
- type: replace
  path: /indicators/0/thresholds
  value:
  - level: critical
      operator: gt
      value: 0
