---
name: indicator-protocol

stemcells:
- alias: default
  os: ubuntu-xenial
  version: latest

releases:
- name: monitoring-indicator-protocol
  version: latest
- name: bpm
  version: latest
- name: routing
  version: latest

instance_groups:
- name: indicator-protocol
  azs:
  - z1
  instances: 3
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: bpm
    release: bpm
  - name: indicator-registry
    release: monitoring-indicator-protocol
  - name: indicator-registry-proxy
    release: monitoring-indicator-protocol
    provides:
      indicator-registry:
        shared: true
        aliases:
        - domain: "indicator-registry.service.internal"
    properties:
      tls:
        ca_cert: ((indicator_protocol_ca.ca))
        server_cert: ((indicator_registry_server_ssl.certificate))
        server_key: ((indicator_registry_server_ssl.private_key))
        server_common_name: indicator-registry
        client_cert: ((indicator_registry_client_ssl.certificate))
        client_key: ((indicator_registry_client_ssl.private_key))
        agent_client_cert: ((indicator_registration_agent_client_ssl.certificate))
        agent_client_key: ((indicator_registration_agent_client_ssl.private_key))
  - name: route_registrar
    release: routing
    consumes:
      nats:
        machines:
        port:
        user:
        password:
    properties:
      route_registrar:
        routes:
        - name: cf-auth-proxy
          port: 5000
          registration_interval: 20s
          uris:
          - indicator-registry.((system_domain))
#          health_check:
#            name: log-store-health
#            script_path: /var/vcap/jobs/log-store/bin/health-check.sh
#            timeout: 5s
  - name: indicator-cf-auth-proxy
    release: monitoring-indicator-protocol
    consumes:
      indicator-registry: {deployment: indicator-protocol}
    provides:
      cf-auth-proxy:
        shared: true
        aliases:
        - domain: "cf-auth-proxy.service.internal"
    properties:
      uaa:
        addr: "https://uaa.madlamp.cf-denver.com" #TODO: parameterize me
      tls:
        client_cert: ((cf_auth_proxy_client_ssl.certificate))
        client_key: ((cf_auth_proxy_client_ssl.private_key))
        server_cert: ((cf_auth_proxy_server_ssl.certificate))
        server_key: ((cf_auth_proxy_server_ssl.private_key))
        server_common_name: indicator-registry
        ca_cert: ((indicator_protocol_ca.ca))
  - name: grafana-dashboard-controller
    release: monitoring-indicator-protocol
    properties:
      output_directory: /var/vcap/data/tmp
      tls:
        client_cert: ((grafana_controller_client_ssl.certificate))
        client_key: ((grafana_controller_client_ssl.private_key))
        ca_cert: ((indicator_protocol_ca.ca))
  - name: prometheus-rules-controller
    release: monitoring-indicator-protocol
    properties:
      output_directory: /var/vcap/data/tmp
      prometheus_uri: http://localhost:12345
      tls:
        client_cert: ((prometheus_controller_client_ssl.certificate))
        client_key: ((prometheus_controller_client_ssl.private_key))
        ca_cert: ((indicator_protocol_ca.ca))
  - name: status-controller
    release: monitoring-indicator-protocol
    properties:
      prometheus_uri: overwritten-by-opsfile
      uaa_uri: overwritten-by-opsfile
      uaa_client_id: overwritten-by-opsfile
      uaa_client_secret: overwritten-by-opsfile
      tls:
        client_cert: overwritten-by-opsfile
        client_key: overwritten-by-opsfile
        ca_cert: overwritten-by-opsfile
  - name: indicator-smoke-tests
    release: monitoring-indicator-protocol
    properties:
      tls:
        client_cert: ((smoke_test_client_ssl.certificate))
        client_key: ((smoke_test_client_ssl.private_key))
        ca_cert: ((indicator_protocol_ca.ca))
update:
  canaries: 0
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

variables:
- name: indicator_protocol_ca
  type: certificate
  options:
    common_name: indicator-protocol-ca
    is_ca: true

- name: indicator_registry_server_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: indicator-registry
    extended_key_usage:
    - server_auth
- name: indicator_registry_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: indicator-registry
    extended_key_usage:
    - client_auth

- name: cf_auth_proxy_server_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: cf-auth-proxy.service.internal
    extended_key_usage:
    - server_auth
- name: cf_auth_proxy_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: cf-auth-proxy
    extended_key_usage:
    - client_auth

- name: grafana_controller_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: grafana-controller
    extended_key_usage:
    - client_auth

- name: prometheus_controller_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: prometheus-controller
    extended_key_usage:
    - client_auth

- name: status_controller_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: status-controller
    extended_key_usage:
    - client_auth

- name: smoke_test_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: smoke_test
    extended_key_usage:
    - client_auth

- name: indicator_registration_agent_client_ssl
  type: certificate
  options:
    ca: indicator_protocol_ca
    common_name: indicator-registration-agent
    extended_key_usage:
    - client_auth

