version: '3'
services:
  indicator-registry:
    image: indicatorprotocol/bosh-indicator-protocol-registry
    expose: ["10568"]
  indicator-registry-proxy:
    image: indicatorprotocol/bosh-indicator-protocol-registry-proxy
    ports: ["10567:10567"]
    volumes: ["./certs:/srv/certs"]
